import Foundation
import QuartzCore

// Parameters are sent by the v1 feed; older companions ignore the optional motion field.
// The default below is generated byte-for-byte from hooks/motion.ts.
struct MotionModel: Codable, Equatable {
    struct Hold: Codable, Equatable {
        var median: Double, sigma: Double, min: Double, max: Double
        func sample(_ random: () -> Double) -> Double {
            let z = sqrt(-2 * log(Swift.max(Double.leastNonzeroMagnitude, random()))) * cos(2 * .pi * random())
            return Swift.max(min, Swift.min(max, median * exp(sigma * z)))
        }
    }
    struct Blink: Codable, Equatable {
        var interval: Hold, shut: Hold, doubleChance: Double, doubleGap: Hold, gazeChance: Double, gazeDelay: Hold
    }
    struct Burst: Codable, Equatable { var min: Int, max: Int, pause: Hold }
    var version: Int, sequenceMs: Double, blink: Blink, think: Hold, work: Hold, wild: Hold, workBurst: Burst
    static let standard = try! JSONDecoder().decode(MotionModel.self, from: Data(defaultJSON.utf8))
    static let defaultJSON = #"{"version":1,"sequenceMs":180000,"blink":{"interval":{"median":5000,"sigma":0.54,"min":1200,"max":20000},"shut":{"median":130,"sigma":0.12,"min":100,"max":160},"doubleChance":0.08333333333333333,"doubleGap":{"median":210,"sigma":0.22,"min":150,"max":300},"gazeChance":0.5,"gazeDelay":{"median":245,"sigma":0.3,"min":150,"max":400}},"think":{"median":1400,"sigma":0.36,"min":800,"max":2600},"work":{"median":330,"sigma":0.25,"min":220,"max":500},"wild":{"median":200,"sigma":0.3,"min":120,"max":320},"workBurst":{"min":3,"max":8,"pause":{"median":1265,"sigma":0.28,"min":800,"max":2000}}}"#
    init?(_ object: Any?) {
        guard let object, let data = try? JSONSerialization.data(withJSONObject: object),
              let model = try? JSONDecoder().decode(Self.self, from: data) else { return nil }
        guard model.version == 1, model.sequenceMs >= 180_000, model.sequenceMs <= 600_000 else { return nil }
        let holds: [Hold] = [model.blink.interval, model.blink.shut, model.blink.doubleGap, model.blink.gazeDelay,
                             model.think, model.work, model.wild, model.workBurst.pause]
        for hold in holds {
            guard hold.median.isFinite, hold.sigma.isFinite, hold.min.isFinite, hold.max.isFinite else { return nil }
            guard hold.min > 0, hold.max >= hold.min, hold.median >= hold.min, hold.median <= hold.max else { return nil }
            guard hold.sigma >= 0, hold.sigma <= 2 else { return nil }
        }
        guard (0...1).contains(model.blink.doubleChance), (0...1).contains(model.blink.gazeChance) else { return nil }
        guard model.workBurst.min >= 1, model.workBurst.max <= 20, model.workBurst.min <= model.workBurst.max else { return nil }
        self = model
    }
    func cycle(_ kind: String, random: @escaping () -> Double) -> () -> Double {
        var changes = 0
        func burst() -> Int { workBurst.min + Int(random() * Double(workBurst.max - workBurst.min + 1)) }
        var left = kind == "work" ? burst() : 0
        return {
            if kind == "work" {
                let old = changes; changes += 1
                if old >= left { changes = 0; left = burst(); return workBurst.pause.sample(random) }
            }
            return (kind == "think" ? think : kind == "wild" ? wild : work).sample(random)
        }
    }
    func loop(first: CGImage, second: CGImage, kind: String, random: @escaping () -> Double = { Double.random(in: 0..<1) }) -> CAKeyframeAnimation {
        let next = cycle(kind, random: random)
        var time = 0.0, secondFrame = false
        var values: [CGImage] = [first], times = [0.0]
        while true {
            time += next()
            if time >= sequenceMs { break }
            secondFrame.toggle(); values.append(secondFrame ? second : first); times.append(time)
        }
        return animation(values: values, times: times, until: time)
    }
    func idle(open: CGImage, shut: CGImage, gaze: Bool, random: @escaping () -> Double = { Double.random(in: 0..<1) }) -> CAKeyframeAnimation {
        var values: [CGImage] = [open], times = [0.0]
        var time = gaze && random() < blink.gazeChance ? blink.gazeDelay.sample(random) : blink.interval.sample(random)
        while time < sequenceMs {
            values.append(shut); times.append(time)
            time += blink.shut.sample(random); values.append(open); times.append(time)
            if random() < blink.doubleChance {
                time += blink.doubleGap.sample(random); values.append(shut); times.append(time)
                time += blink.shut.sample(random); values.append(open); times.append(time)
            }
            time += blink.interval.sample(random)
        }
        return animation(values: values, times: times, until: time)
    }
    private func animation(values: [CGImage], times: [Double], until durationMs: Double) -> CAKeyframeAnimation {
        let result = CAKeyframeAnimation(keyPath: "contents")
        // CAAnimation.h: each key time corresponds to one contents value. The endpoint
        // repeats the last frame, preserving its whole sampled hold at the repeat seam.
        result.values = values + [values.last!]
        result.keyTimes = (times + [durationMs]).map { NSNumber(value: $0 / durationMs) }
        result.calculationMode = .discrete
        result.duration = durationMs / 1000
        result.repeatCount = .infinity
        result.isRemovedOnCompletion = false
        return result
    }
}
