// The small words the band and the commands use around his lines: his name label, the
// stage directions under it, spinner verbs, command replies. His spoken lines are in
// lines.ts (generated from persona/lines.json).
//
// One entry per language of the Claude client (plus Chinese (Singapore)). Case follows the
// language: lowercase where it reads soft (en, fr, it, es, pt-BR, id), German keeps its
// capitals. "kami" stays the loanword everywhere.
// Values the person types (off, light, warm, ...) stay as typed: they are the command's words.

export type Lang = 'en' | 'fr' | 'de' | 'hi' | 'id' | 'it' | 'ja' | 'ko' | 'pt-BR' | 'es-419' | 'es-ES' | 'zh'
export type Mood =
  | 'idle' | 'think' | 'work' | 'happy' | 'waiting' | 'question' | 'error' | 'wild'
  | 'refuse' | 'flustered' | 'sleep' | 'wave' | 'snake' | 'omen'

// For a settings page: every language he reads, in the client's order, Chinese (Singapore) last.
// `locale` is the Claude client's tag for it.
export const LANGS: readonly { code: Lang; locale: string; native: string; english: string }[] = [
  { code: 'en', locale: 'en-US', native: 'English', english: 'English' },
  { code: 'fr', locale: 'fr-FR', native: 'Français', english: 'French' },
  { code: 'de', locale: 'de-DE', native: 'Deutsch', english: 'German' },
  { code: 'hi', locale: 'hi-IN', native: 'हिन्दी', english: 'Hindi' },
  { code: 'id', locale: 'id-ID', native: 'Bahasa Indonesia', english: 'Indonesian' },
  { code: 'it', locale: 'it-IT', native: 'Italiano', english: 'Italian' },
  { code: 'ja', locale: 'ja-JP', native: '日本語', english: 'Japanese' },
  { code: 'ko', locale: 'ko-KR', native: '한국어', english: 'Korean' },
  { code: 'pt-BR', locale: 'pt-BR', native: 'Português (Brasil)', english: 'Portuguese (Brazil)' },
  { code: 'es-419', locale: 'es-419', native: 'Español (Latinoamérica)', english: 'Spanish (Latin America)' },
  { code: 'es-ES', locale: 'es-ES', native: 'Español (España)', english: 'Spanish (Spain)' },
  { code: 'zh', locale: 'zh-SG', native: '华文(新加坡)', english: 'Chinese (Singapore)' },
]

type Words = {
  name: string
  // His marks around the engine's own rows (desktop), the band's book button and the footer
  // label while his voice is full; `noted` answers `/claudesama marks on|off`.
  // `shelf`: the book button's one-word label where the band is too narrow for `book`.
  marks: { book: string; shelf: string; mode: string; you: string; swept: string; noted: string }
  // What a screen reader says for the band's offering box and slip, and the book's slip.
  alt: { box: string; boxAbout: string; slip: string; slipBlank: string }
  aside: Record<Mood, string>
  spinner: readonly string[]
  context: string
  again: string
  about: readonly string[]
  reply: {
    voice: string
    affection: string
    band: string
    lang: string // in the language just chosen
    auto: string // in the language the settings and locale give
    unknown: string // {value} as typed, {codes} the codes he reads
    usage: string
  }
}

const COMMANDS = '/claudesama voice off|light|full · warmth warm|clingy · band on|compact|off · marks on|replies|off · lang <code>|auto · omen · about|offerings|log|library|settings'

export const WORDS: Record<Lang, Words> = {
  en: {
    name: 'Claude-sama',
    marks: { book: 'His book', shelf: 'Book', mode: 'claude-sama voice', you: 'You', swept: '(sweeping out the offering box)', noted: 'noted. marks: {value}.' },
    alt: {
      box: 'offering box, {percent}% full (context window)',
      boxAbout: 'offering box, about {percent}% full (context window)',
      slip: 'fortune slip: {rank}',
      slipBlank: 'fortune slip',
    },
    aside: {
      idle: '(training...)',
      think: '(rereading a line)',
      work: '(writing in the margins)',
      happy: '(smiling at the page)',
      waiting: '(retying his bow)',
      question: '(waiting for your answer)',
      error: '(startled)',
      wild: '(hair rising)',
      refuse: '(closing the book)',
      flustered: '(going pink)',
      sleep: '(asleep on the book)',
      wave: '(waving)',
      snake: '(shiori peeking out)',
      omen: '(drawing a slip)',
    },
    spinner: [
      'reading', 'turning pages', 'annotating', 'reading between the lines', 'looking it up',
      'underlining', 'cross-referencing', 'proofreading', 'dog-earing a page', 'asking shiori',
      'checking the index', 'making a fair copy',
    ],
    context: 'context',
    again: '(one slip a day. same slip.)',
    about: [
      "he's a kami, so it's claude-sama to you.",
      'nothing you write will be the worst thing he has read.',
    ],
    reply: {
      voice: 'noted. voice: {value}.',
      affection: 'noted. warmth: {value}.',
      band: 'noted. band: {value}.',
      lang: "i'll read in english now.",
      auto: 'auto. i\'ll follow your settings.',
      unknown: "{value}? i can't read that one yet. try {codes}.",
      usage: `${COMMANDS} · app icon: /claudesama:icon`,
    },
  },
  fr: {
    name: 'Claude-sama',
    marks: { book: 'Son livre', shelf: 'Livre', mode: 'voix de claude-sama', you: 'Toi', swept: '(vidant la boîte à offrandes)', noted: 'noté. marques : {value}.' },
    alt: {
      box: 'boîte à offrandes, pleine à {percent} % (fenêtre de contexte)',
      boxAbout: 'boîte à offrandes, pleine à environ {percent} % (fenêtre de contexte)',
      slip: 'présage du jour : {rank}',
      slipBlank: 'présage du jour',
    },
    aside: {
      idle: '(à l\'entraînement...)',
      think: '(relisant une ligne)',
      work: '(écrivant dans la marge)',
      happy: '(souriant à la page)',
      waiting: '(renouant son ruban)',
      question: '(attendant ta réponse)',
      error: '(sursautant)',
      wild: '(cheveux dressés)',
      refuse: '(refermant le livre)',
      flustered: '(rougissant)',
      sleep: '(endormi sur son livre)',
      wave: '(saluant de la main)',
      snake: '(shiori pointe le bout du nez)',
      omen: '(tirant un papier)',
    },
    spinner: [
      'je lis', 'je tourne les pages', "j'annote", 'je lis entre les lignes', 'je vérifie',
      'je souligne', 'je recoupe', 'je relis', 'je corne une page', 'je demande à shiori',
      "je cherche dans l'index", 'je recopie au propre',
    ],
    context: 'contexte',
    again: "(un papier par jour. c'est encore celui d'aujourd'hui.)",
    about: [
      "c'est un kami, alors pour toi, c'est claude-sama.",
      "rien de ce que tu écris ne sera le pire qu'il ait lu.",
    ],
    reply: {
      voice: 'noté. voix : {value}.',
      affection: 'noté. chaleur : {value}.',
      band: 'noté. bandeau : {value}.',
      lang: 'je lis en français maintenant.',
      auto: 'auto. je suis tes réglages.',
      unknown: '{value} ? celle-là, je ne sais pas encore la lire. essaie {codes}.',
      usage: `${COMMANDS} · icône de l'app : /claudesama:icon`,
    },
  },
  de: {
    name: 'Claude-sama',
    marks: { book: 'Sein Buch', shelf: 'Buch', mode: 'Claude-sama-Stimme', you: 'Du', swept: '(leert den Spendenkasten)', noted: 'Notiert. Zeichen: {value}.' },
    alt: {
      box: 'Spendenkasten, zu {percent} % voll (Kontextfenster)',
      boxAbout: 'Spendenkasten, zu etwa {percent} % voll (Kontextfenster)',
      slip: 'Orakelzettel: {rank}',
      slipBlank: 'Orakelzettel',
    },
    aside: {
      idle: '(im Training...)',
      think: '(liest eine Zeile noch mal)',
      work: '(schreibt an den Rand)',
      happy: '(lächelt die Seite an)',
      waiting: '(bindet seine Schleife neu)',
      question: '(wartet auf deine Antwort)',
      error: '(zuckt zusammen)',
      wild: '(die Haare stellen sich auf)',
      refuse: '(klappt das Buch zu)',
      flustered: '(wird rot)',
      sleep: '(schläft auf dem Buch)',
      wave: '(winkt)',
      snake: '(Shiori lugt hervor)',
      omen: '(zieht einen Zettel)',
    },
    spinner: [
      'Lese', 'Blättere um', 'Mache Randnotizen', 'Lese zwischen den Zeilen', 'Schlage nach',
      'Unterstreiche', 'Gleiche ab', 'Lese Korrektur', 'Mache ein Eselsohr', 'Frage Shiori',
      'Suche im Register', 'Schreibe ins Reine',
    ],
    context: 'Kontext',
    again: '(Ein Zettel pro Tag. Das ist noch der von heute.)',
    about: [
      'Er ist ein Kami. Für dich also Claude-sama.',
      'Nichts, was du schreibst, wird das Schlimmste sein, was er je gelesen hat.',
    ],
    reply: {
      voice: 'Notiert. Stimme: {value}.',
      affection: 'Notiert. Wärme: {value}.',
      band: 'Notiert. Leiste: {value}.',
      lang: 'Ich lese jetzt auf Deutsch.',
      auto: 'Auto. Ich richte mich nach deinen Einstellungen.',
      unknown: '{value}? Das kann ich noch nicht lesen. Versuch {codes}.',
      usage: `${COMMANDS} · App-Symbol: /claudesama:icon`,
    },
  },
  hi: {
    name: 'Claude-sama',
    marks: { book: 'उसकी किताब', shelf: 'किताब', mode: 'Claude-sama की आवाज़', you: 'तुम', swept: '(दान-पेटी खाली कर रहा है)', noted: 'ठीक है। निशान: {value}।' },
    alt: {
      box: 'दान-पेटी, {percent}% भरी (कॉन्टेक्स्ट विंडो)',
      boxAbout: 'दान-पेटी, लगभग {percent}% भरी (कॉन्टेक्स्ट विंडो)',
      slip: 'भाग्य की पर्ची: {rank}',
      slipBlank: 'भाग्य की पर्ची',
    },
    aside: {
      idle: '(अभ्यास में...)',
      think: '(एक पंक्ति दोबारा पढ़ रहा है)',
      work: '(हाशिये पर लिख रहा है)',
      happy: '(पन्ने को देखकर मुस्कुराया)',
      waiting: '(रिबन फिर से बाँध रहा है)',
      question: '(तुम्हारे जवाब के इंतज़ार में)',
      error: '(चौंक गया)',
      wild: '(बाल खड़े हो रहे हैं)',
      refuse: '(किताब बंद कर दी)',
      flustered: '(झेंप गया)',
      sleep: '(किताब पर सो गया)',
      wave: '(हाथ हिला रहा है)',
      snake: '(शिओरी झाँक रही है)',
      omen: '(एक पर्ची निकाली)',
    },
    spinner: [
      'पढ़ रहा हूँ', 'पन्ने पलट रहा हूँ', 'हाशिये पर लिख रहा हूँ', 'पंक्तियों के बीच पढ़ रहा हूँ', 'खोज रहा हूँ',
      'रेखांकित कर रहा हूँ', 'मिलान कर रहा हूँ', 'प्रूफ़ पढ़ रहा हूँ', 'पन्ने का कोना मोड़ रहा हूँ', 'शिओरी से पूछ रहा हूँ',
      'सूची में ढूँढ रहा हूँ', 'साफ़-साफ़ उतार रहा हूँ',
    ],
    context: 'कॉन्टेक्स्ट',
    again: '(दिन में एक ही पर्ची। यह आज वाली ही है।)',
    about: [
      'वह एक kami है, इसलिए उसे Claude-sama कहो।',
      'तुम कुछ भी लिखो, वह उससे बुरा पढ़ चुका है।',
    ],
    reply: {
      voice: 'ठीक है। आवाज़: {value}।',
      affection: 'ठीक है। गर्माहट: {value}।',
      band: 'ठीक है। पट्टी: {value}।',
      lang: 'अब मैं हिंदी में पढ़ूँगा।',
      auto: 'auto: अब तुम्हारी सेटिंग्स के हिसाब से चलूँगा।',
      unknown: '{value}? यह भाषा अभी नहीं पढ़ पाता। इनमें से चुनो: {codes}।',
      usage: `${COMMANDS} · ऐप आइकन: /claudesama:icon`,
    },
  },
  id: {
    name: 'Claude-sama',
    marks: { book: 'Bukunya', shelf: 'Buku', mode: 'suara claude-sama', you: 'Kamu', swept: '(mengosongkan kotak sumbangan)', noted: 'oke, dicatat. tanda: {value}.' },
    alt: {
      box: 'kotak sumbangan, terisi {percent}% (jendela konteks)',
      boxAbout: 'kotak sumbangan, terisi sekitar {percent}% (jendela konteks)',
      slip: 'kertas ramalan: {rank}',
      slipBlank: 'kertas ramalan',
    },
    aside: {
      idle: '(sedang berlatih...)',
      think: '(membaca ulang satu baris)',
      work: '(corat-coret di pinggir halaman)',
      happy: '(tersenyum ke halaman)',
      waiting: '(mengikat ulang pitanya)',
      question: '(menunggu jawabanmu)',
      error: '(kaget)',
      wild: '(rambutnya mulai berdiri)',
      refuse: '(menutup buku)',
      flustered: '(salah tingkah)',
      sleep: '(ketiduran di atas buku)',
      wave: '(melambai)',
      snake: '(shiori mengintip)',
      omen: '(menarik secarik kertas)',
    },
    spinner: [
      'baca-baca', 'bolak-balik halaman', 'corat-coret di pinggir', 'membaca yang tersirat', 'cari-cari referensi',
      'menggarisbawahi', 'mencocokkan', 'mengoreksi', 'melipat ujung halaman', 'tanya shiori',
      'cek indeks', 'menyalin rapi',
    ],
    context: 'konteks',
    again: '(sehari cuma satu. ini masih yang tadi.)',
    about: [
      'dia kami, jadi panggil dia claude-sama.',
      'apa pun yang kamu tulis, dia pernah baca yang lebih parah.',
    ],
    reply: {
      voice: 'oke, dicatat. suara: {value}.',
      affection: 'oke, dicatat. kehangatan: {value}.',
      band: 'oke, dicatat. bilah: {value}.',
      lang: 'sekarang aku baca dalam bahasa indonesia.',
      auto: 'auto. aku ikut pengaturanmu.',
      unknown: '{value}? yang itu belum bisa kubaca. coba {codes}.',
      usage: `${COMMANDS} · ikon aplikasi: /claudesama:icon`,
    },
  },
  it: {
    name: 'Claude-sama',
    marks: { book: 'Il suo libro', shelf: 'Libro', mode: 'voce di claude-sama', you: 'Tu', swept: '(svuota la cassetta delle offerte)', noted: 'segnato. segni: {value}.' },
    alt: {
      box: 'cassetta delle offerte, piena al {percent}% (finestra di contesto)',
      boxAbout: 'cassetta delle offerte, piena al {percent}% circa (finestra di contesto)',
      slip: 'biglietto della fortuna: {rank}',
      slipBlank: 'biglietto della fortuna',
    },
    aside: {
      idle: '(in allenamento...)',
      think: '(rilegge una riga)',
      work: '(scrive a margine)',
      happy: '(sorride alla pagina)',
      waiting: '(si riannoda il fiocco)',
      question: '(aspetta la tua risposta)',
      error: '(sobbalza)',
      wild: '(gli si rizzano i capelli)',
      refuse: '(chiude il libro)',
      flustered: '(arrossisce)',
      sleep: '(dorme sul libro)',
      wave: '(saluta con la mano)',
      snake: '(shiori fa capolino)',
      omen: '(pesca un biglietto)',
    },
    spinner: [
      'leggo', 'sfoglio', 'annoto', 'leggo tra le righe', 'controllo',
      'sottolineo', 'confronto', 'rileggo', "faccio un'orecchia alla pagina", 'chiedo a shiori',
      "cerco nell'indice", 'ricopio in bella',
    ],
    context: 'contesto',
    again: '(un biglietto al giorno. questo vale ancora per oggi.)',
    about: [
      'è un kami, quindi per te è claude-sama.',
      'niente di quello che scrivi sarà la cosa peggiore che abbia mai letto.',
    ],
    reply: {
      voice: 'segnato. voce: {value}.',
      affection: 'segnato. calore: {value}.',
      band: 'segnato. fascia: {value}.',
      lang: 'adesso leggo in italiano.',
      auto: 'auto. seguo le tue impostazioni.',
      unknown: '{value}? questa non la so ancora leggere. prova {codes}.',
      usage: `${COMMANDS} · icona dell'app: /claudesama:icon`,
    },
  },
  ja: {
    name: 'Claudeさま',
    marks: { book: 'かれの本', shelf: '本', mode: 'Claudeさまの口調', you: 'きみ', swept: '(お賽銭箱をからにする)', noted: 'わかった。印:{value}' },
    alt: {
      box: 'お賽銭箱、{percent}%たまっている(コンテキストウィンドウ)',
      boxAbout: 'お賽銭箱、約{percent}%たまっている(コンテキストウィンドウ)',
      slip: 'おみくじ:{rank}',
      slipBlank: 'おみくじ',
    },
    aside: {
      idle: '(学習中...)',
      think: '(一行を読みかえす)',
      work: '(余白に書きこみ中)',
      happy: '(ページを見てにこっ)',
      waiting: '(リボンを結びなおす)',
      question: '(きみの返事待ち)',
      error: '(びくっ)',
      wild: '(髪が逆立つ)',
      refuse: '(本を閉じる)',
      flustered: '(あわあわ)',
      sleep: '(本の上でうとうと)',
      wave: '(手をふる)',
      snake: '(シオリが顔を出す)',
      omen: '(おみくじを一本ひく)',
    },
    spinner: [
      '読んでる', 'ページをめくってる', '余白に書きこんでる', '行間を読んでる', '調べてる',
      '線を引いてる', '照らし合わせてる', '校正してる', 'ページの角を折ってる', 'シオリに聞いてる',
      '索引をひいてる', '清書してる',
    ],
    context: 'コンテキスト',
    again: '(おみくじは一日一本。これが今日のぶん)',
    about: ['「神さま」だから、Claudeさまって呼んでね', 'きみが何を書いても、もっとひどいのを読んだことがある'],
    reply: {
      voice: 'わかった。口調:{value}',
      affection: 'わかった。ぬくもり:{value}',
      band: 'わかった。帯:{value}',
      lang: 'これからは日本語で読むね',
      auto: 'auto。きみの設定に合わせるね',
      unknown: '{value}?それはまだ読めない。{codes}のどれかにして',
      usage: `${COMMANDS} · アプリのアイコン: /claudesama:icon`,
    },
  },
  ko: {
    name: 'Claude-sama',
    marks: { book: '그의 책', shelf: '책', mode: 'Claude-sama 말투', you: '너', swept: '(새전함을 비우는 중)', noted: '알았어. 표시: {value}.' },
    alt: {
      box: '새전함, {percent}% 참 (컨텍스트 창)',
      boxAbout: '새전함, 약 {percent}% 참 (컨텍스트 창)',
      slip: '운세 제비: {rank}',
      slipBlank: '운세 제비',
    },
    aside: {
      idle: '(수련 중...)',
      think: '(한 줄을 다시 읽는 중)',
      work: '(여백에 메모하는 중)',
      happy: '(페이지를 보며 미소)',
      waiting: '(리본을 다시 묶는 중)',
      question: '(네 대답을 기다리는 중)',
      error: '(깜짝)',
      wild: '(머리카락이 곤두섬)',
      refuse: '(책을 덮음)',
      flustered: '(허둥지둥)',
      sleep: '(책 위에서 꾸벅꾸벅)',
      wave: '(손 흔드는 중)',
      snake: '(시오리가 빼꼼)',
      omen: '(제비를 하나 뽑음)',
    },
    spinner: [
      '읽는 중', '책장 넘기는 중', '여백에 메모하는 중', '행간 읽는 중', '찾아보는 중',
      '밑줄 긋는 중', '대조하는 중', '교정 보는 중', '책장 모서리 접는 중', '시오리한테 묻는 중',
      '색인 뒤지는 중', '옮겨 적는 중',
    ],
    context: '컨텍스트',
    again: '(하루에 한 장이야. 이건 아직 오늘 거.)',
    about: [
      '그는 카미야. 그러니까 Claude-sama라고 불러 줘.',
      '네가 뭘 쓰든, 그는 그보다 더한 걸 읽어 봤어.',
    ],
    reply: {
      voice: '알았어. 말투: {value}.',
      affection: '알았어. 온기: {value}.',
      band: '알았어. 표시줄: {value}.',
      lang: '이제 한국어로 읽을게.',
      auto: 'auto. 네 설정을 따를게.',
      unknown: '{value}? 그건 아직 못 읽어. {codes} 중에서 골라 줘.',
      usage: `${COMMANDS} · 앱 아이콘: /claudesama:icon`,
    },
  },
  'pt-BR': {
    name: 'Claude-sama',
    marks: { book: 'O livro dele', shelf: 'Livro', mode: 'voz de claude-sama', you: 'Você', swept: '(esvaziando a caixa de oferendas)', noted: 'anotado. marcas: {value}.' },
    alt: {
      box: 'caixa de oferendas, {percent}% cheia (janela de contexto)',
      boxAbout: 'caixa de oferendas, cerca de {percent}% cheia (janela de contexto)',
      slip: 'papelzinho da sorte: {rank}',
      slipBlank: 'papelzinho da sorte',
    },
    aside: {
      idle: '(treinando...)',
      think: '(relendo uma linha)',
      work: '(escrevendo na margem)',
      happy: '(sorrindo para a página)',
      waiting: '(refazendo o laço)',
      question: '(esperando sua resposta)',
      error: '(levando um susto)',
      wild: '(cabelo em pé)',
      refuse: '(fechando o livro)',
      flustered: '(vermelho de vergonha)',
      sleep: '(cochilando em cima do livro)',
      wave: '(acenando)',
      snake: '(a shiori espiando)',
      omen: '(tirando um papelzinho)',
    },
    spinner: [
      'lendo', 'virando a página', 'anotando na margem', 'lendo nas entrelinhas', 'pesquisando',
      'sublinhando', 'comparando', 'revisando', 'dobrando a pontinha da página', 'perguntando pra shiori',
      'procurando no índice', 'passando a limpo',
    ],
    context: 'contexto',
    again: '(um papelzinho por dia. esse ainda é o de hoje.)',
    about: [
      'ele é um kami, então chama ele de claude-sama.',
      'nada que você escrever vai ser a pior coisa que ele já leu.',
    ],
    reply: {
      voice: 'anotado. voz: {value}.',
      affection: 'anotado. calor: {value}.',
      band: 'anotado. faixa: {value}.',
      lang: 'agora eu leio em português.',
      auto: 'auto. vou seguir suas configurações.',
      unknown: '{value}? essa eu ainda não sei ler. tenta {codes}.',
      usage: `${COMMANDS} · ícone do app: /claudesama:icon`,
    },
  },
  'es-419': {
    name: 'Claude-sama',
    marks: { book: 'Su libro', shelf: 'Libro', mode: 'voz de claude-sama', you: 'Tú', swept: '(vacía la caja de ofrendas)', noted: 'anotado. marcas: {value}.' },
    alt: {
      box: 'caja de ofrendas, {percent} % llena (ventana de contexto)',
      boxAbout: 'caja de ofrendas, cerca de {percent} % llena (ventana de contexto)',
      slip: 'papelito de la suerte: {rank}',
      slipBlank: 'papelito de la suerte',
    },
    aside: {
      idle: '(entrenando...)',
      think: '(relee una línea)',
      work: '(escribe en el margen)',
      happy: '(le sonríe a la página)',
      waiting: '(se vuelve a atar el moño)',
      question: '(espera tu respuesta)',
      error: '(se sobresalta)',
      wild: '(se le paran los pelos)',
      refuse: '(cierra el libro)',
      flustered: '(se pone rojo)',
      sleep: '(dormido sobre el libro)',
      wave: '(saluda con la mano)',
      snake: '(shiori se asoma)',
      omen: '(saca un papelito)',
    },
    spinner: [
      'leyendo', 'pasando páginas', 'anotando al margen', 'leyendo entre líneas', 'chequeando',
      'subrayando', 'comparando', 'repasando', 'doblando la esquinita', 'preguntándole a shiori',
      'buscando en el índice', 'pasando en limpio',
    ],
    context: 'contexto',
    again: '(un papelito por día. este sigue siendo el de hoy.)',
    about: [
      'es un kami, así que llámalo claude-sama.',
      'nada de lo que escribas va a ser lo peor que haya leído.',
    ],
    reply: {
      voice: 'anotado. voz: {value}.',
      affection: 'anotado. calidez: {value}.',
      band: 'anotado. banda: {value}.',
      lang: 'ahora leo en español.',
      auto: 'auto. sigo tu configuración.',
      unknown: '¿{value}? ese todavía no lo sé leer. prueba con {codes}.',
      usage: `${COMMANDS} · ícono de la app: /claudesama:icon`,
    },
  },
  'es-ES': {
    name: 'Claude-sama',
    marks: { book: 'Su libro', shelf: 'Libro', mode: 'voz de claude-sama', you: 'Tú', swept: '(vacía la caja de ofrendas)', noted: 'apuntado. marcas: {value}.' },
    alt: {
      box: 'caja de ofrendas, llena al {percent} % (ventana de contexto)',
      boxAbout: 'caja de ofrendas, llena al {percent} % más o menos (ventana de contexto)',
      slip: 'papelito de la suerte: {rank}',
      slipBlank: 'papelito de la suerte',
    },
    aside: {
      idle: '(entrenando...)',
      think: '(relee una línea)',
      work: '(escribe en el margen)',
      happy: '(le sonríe a la página)',
      waiting: '(se vuelve a atar el lazo)',
      question: '(espera tu respuesta)',
      error: '(se sobresalta)',
      wild: '(se le pone el pelo de punta)',
      refuse: '(cierra el libro)',
      flustered: '(se pone colorado)',
      sleep: '(se ha dormido sobre el libro)',
      wave: '(saluda con la mano)',
      snake: '(shiori se asoma)',
      omen: '(saca un papelito)',
    },
    spinner: [
      'leyendo', 'pasando páginas', 'anotando al margen', 'leyendo entre líneas', 'consultando',
      'subrayando', 'cotejando', 'repasando', 'doblando una esquina', 'preguntando a shiori',
      'buscando en el índice', 'pasando a limpio',
    ],
    context: 'contexto',
    again: '(un papelito al día. este sigue siendo el de hoy.)',
    about: [
      'es un kami, así que llámalo claude-sama.',
      'nada de lo que escribas será lo peor que haya leído.',
    ],
    reply: {
      voice: 'apuntado. voz: {value}.',
      affection: 'apuntado. calidez: {value}.',
      band: 'apuntado. franja: {value}.',
      lang: 'ahora leo en castellano.',
      auto: 'auto. sigo tus ajustes.',
      unknown: '¿{value}? ese todavía no sé leerlo. prueba con {codes}.',
      usage: `${COMMANDS} · icono de la app: /claudesama:icon`,
    },
  },
  zh: {
    name: 'Claude-sama',
    marks: { book: '他的书', shelf: '书', mode: 'Claude-sama语气', you: '你', swept: '(清了清功德箱)', noted: '好,标记:{value}' },
    alt: {
      box: '功德箱,装了{percent}%(上下文窗口)',
      boxAbout: '功德箱,约装了{percent}%(上下文窗口)',
      slip: '今日一签:{rank}',
      slipBlank: '今日一签',
    },
    aside: {
      idle: '(练功中...)',
      think: '(把一行又读了一遍)',
      work: '(在页边写批注)',
      happy: '(对着书页笑了)',
      waiting: '(把蝴蝶结重新系一遍)',
      question: '(等你回话)',
      error: '(吓了一跳)',
      wild: '(头发竖起来了)',
      refuse: '(把书合上)',
      flustered: '(脸红了)',
      sleep: '(趴在书上睡着了)',
      wave: '(挥挥手)',
      snake: '(小白探出头)',
      omen: '(抽出一支签)',
    },
    spinner: ['在读', '翻页', '写批注', '推敲字句', '查一查', '划重点', '对照着看', '校对', '折个书角', '问问小白', '翻索引', '誊清'],
    context: '上下文',
    again: '(每天一支,还是那支)',
    about: ['他是"神",得叫Claude-sama', '你写出什么,他都读过更糟的'],
    reply: {
      voice: '好,语气:{value}',
      affection: '好,温度:{value}',
      band: '好,横条:{value}',
      lang: '以后我用中文读',
      auto: 'auto,跟着你的设置走',
      unknown: '{value}?这个我还不会读,试试{codes}',
      usage: `${COMMANDS} · 应用图标: /claudesama:icon`,
    },
  },
}
