#!/usr/bin/env python3
"""Regenerate plugin/hooks/lines.ts and plugin/hooks/voice.ts from the files in persona/.

    python3 tools/build-lines.py            # write both files
    python3 tools/build-lines.py --check    # write nothing; exit 1 if either file would change

  persona/lines.json        everything he says in the band, per language  ->  plugin/hooks/lines.ts
  persona/voice-prompt.md   the two system-prompt sections, light and full  ->  plugin/hooks/voice.ts

Edit the persona files, never the generated modules. The output is deterministic, byte for byte,
so CI can run this and fail if a committed module differs from its source. Standard library only.
Exit status: 0 done (or --check found nothing to change), 1 a source is malformed or --check found
a difference.
"""
import argparse
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PERSONA = os.path.join(ROOT, 'persona')
HOOKS = os.path.join(ROOT, 'plugin', 'hooks')


def lines_module():
    """persona/lines.json as plugin/hooks/lines.ts, plus the fortune weights read from omikuji._about."""
    with open(os.path.join(PERSONA, 'lines.json'), encoding='utf-8') as f:
        src = json.load(f)
    ranks = [k for k in src['omikuji'].get('en', {})]
    found = dict(re.findall(r'\b([a-z]+)\s+(\d+)\b', src['omikuji'].get('_about', '')))
    weights = {rank: int(found[rank]) for rank in ranks if rank in found}
    if set(weights) != set(ranks):
        raise SystemExit(f'persona/lines.json omikuji._about gives no weight for: {sorted(set(ranks) - set(weights))}')
    body = json.dumps({k: v for k, v in src.items() if k != '_about'}, ensure_ascii=False, indent=2)
    ts = ('// GENERATED by tools/build-lines.py from persona/lines.json. Do not edit here:\n'
          '// edit persona/lines.json and rebuild. Everything he says in the band.\n'
          '// English lines are all lowercase by rule; {pages} is filled in by the plugin.\n\n'
          f'export const LINES = {body} as const\n\n'
          '// Omikuji draw weights, from omikuji._about in persona/lines.json.\n'
          f'export const OMIKUJI_WEIGHTS: Record<string, number> = {json.dumps(weights)}\n')
    return ts, weights


def voice_module():
    """The ```text blocks under "## light" and "## full" in persona/voice-prompt.md as plugin/hooks/voice.ts."""
    with open(os.path.join(PERSONA, 'voice-prompt.md'), encoding='utf-8') as f:
        md = f.read()
    sections = {}
    for level in ('light', 'full'):
        m = re.search(r'##\s+' + level + r'[^\n]*\n+```text\n(.*?)```', md, re.S)
        if not m:
            raise SystemExit(f'voice-prompt.md: no ```text block under "## {level}"')
        sections[level] = m.group(1).strip()
    return ('// GENERATED by tools/build-lines.py from persona/voice-prompt.md. Do not edit here.\n'
            '// The system-prompt section /claudesama voice light|full adds (off adds nothing).\n\n'
            f'export const VOICE = {json.dumps(sections, ensure_ascii=False, indent=2)} as const\n')


def build_lines():
    """Write plugin/hooks/lines.ts; return the fortune weights."""
    ts, weights = lines_module()
    write(os.path.join(HOOKS, 'lines.ts'), ts)
    return weights


def build_voice():
    """Write plugin/hooks/voice.ts."""
    write(os.path.join(HOOKS, 'voice.ts'), voice_module())


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)


def differs(path, text):
    try:
        with open(path, 'rb') as f:
            return f.read() != text.encode('utf-8')
    except FileNotFoundError:
        return True


def main():
    ap = argparse.ArgumentParser(description='Regenerate plugin/hooks/lines.ts and voice.ts from persona/.')
    ap.add_argument('--check', action='store_true', help='write nothing; exit 1 if either file would change')
    args = ap.parse_args()
    lines_ts, weights = lines_module()
    outputs = [(os.path.join(HOOKS, 'lines.ts'), lines_ts), (os.path.join(HOOKS, 'voice.ts'), voice_module())]
    stale = [path for path, text in outputs if differs(path, text)]
    for path, text in outputs:
        name = os.path.relpath(path, ROOT)
        if args.check:
            print(('differs: ' if path in stale else 'ok:      ') + name)
        elif path in stale:
            write(path, text)
            print(f'wrote     {name} ({len(text.encode("utf-8"))} bytes)')
        else:
            print(f'unchanged {name}')
    if not args.check:
        print(f'omikuji weights: {weights}')
    return 1 if (args.check and stale) else 0


if __name__ == '__main__':
    sys.exit(main())
